/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lecturehelper;

import java.io.*;
import java.time.*;
import java.util.*;

import org.testng.*;
import org.testng.annotations.*;

public class ProtocolsFolderInitializerTest {

    @DataProvider
    public Object[][] toLocalDateTimeData() {
        return new Object[][] {
            {
                "24101109454",
                List.of(
                    LocalDateTime.of(2024, 10, 11, 9, 45),
                    LocalDateTime.of(2024, 10, 11, 10, 30),
                    LocalDateTime.of(2024, 10, 11, 11, 30),
                    LocalDateTime.of(2024, 10, 11, 12, 15)
                )
            }
        };
    }

    @Test(dataProvider="toLocalDateTimeData")
    public void toLocalDateTimeTest(final String date, final List<LocalDateTime> expected) throws IOException {
        Assert.assertEquals(ProtocolsFolderInitializer.toLocalDateTime(date).toList(), expected);
    }

}
